# Generated by Django 4.1.3 on 2022-11-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employeemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('salary', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cname', models.CharField(max_length=40)),
                ('dname', models.CharField(max_length=40)),
            ],
        ),
    ]
