# Generated by Django 4.1.3 on 2022-11-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_employeemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='cname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='dname',
            field=models.CharField(max_length=20),
        ),
    ]
