# Generated by Django 4.1.3 on 2022-11-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_employeemodel_cname_alter_employeemodel_dname'),
    ]

    operations = [
        migrations.CreateModel(
            name='filemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='newapp/static')),
            ],
        ),
    ]
