# Generated by Django 4.1.3 on 2022-11-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_cardmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='xammodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='newapp/static')),
            ],
        ),
    ]
